//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.Report.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CRMReportEntities : DbContext
    {
        public CRMReportEntities()
            : base("name=CRMReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TM_Act_CommunicationTemplet> TM_Act_CommunicationTemplet { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_area> V_M_TM_SYS_BaseData_area { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_brand> V_M_TM_SYS_BaseData_brand { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_channel> V_M_TM_SYS_BaseData_channel { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_colors> V_M_TM_SYS_BaseData_colors { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_customerlevel> V_M_TM_SYS_BaseData_customerlevel { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_product> V_M_TM_SYS_BaseData_product { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_productBrand> V_M_TM_SYS_BaseData_productBrand { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_productCategory> V_M_TM_SYS_BaseData_productCategory { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_productline1> V_M_TM_SYS_BaseData_productline1 { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_productline2> V_M_TM_SYS_BaseData_productline2 { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_promotion> V_M_TM_SYS_BaseData_promotion { get; set; }
        public DbSet<V_M_TM_SYS_BaseData_store> V_M_TM_SYS_BaseData_store { get; set; }
        public DbSet<TL_WX_MemberSign> TL_WX_MemberSign { get; set; }
    
        public virtual ObjectResult<sp_Rpt_MarketActivityTracking_Result> sp_Rpt_MarketActivityTracking(Nullable<System.DateTime> searchdate, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var searchdateParameter = searchdate.HasValue ?
                new ObjectParameter("searchdate", searchdate) :
                new ObjectParameter("searchdate", typeof(System.DateTime));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_MarketActivityTracking_Result>("sp_Rpt_MarketActivityTracking", searchdateParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_Mem_Activitycount_Result> sp_Rpt_Mem_Activitycount(Nullable<System.DateTime> dateBegin2, Nullable<System.DateTime> dateEnd2, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var dateBegin2Parameter = dateBegin2.HasValue ?
                new ObjectParameter("dateBegin2", dateBegin2) :
                new ObjectParameter("dateBegin2", typeof(System.DateTime));
    
            var dateEnd2Parameter = dateEnd2.HasValue ?
                new ObjectParameter("dateEnd2", dateEnd2) :
                new ObjectParameter("dateEnd2", typeof(System.DateTime));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_Mem_Activitycount_Result>("sp_Rpt_Mem_Activitycount", dateBegin2Parameter, dateEnd2Parameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_Mem_ConsumptionFrequency_Count_Result> sp_Rpt_Mem_ConsumptionFrequency_Count(string channel, string brand, string category, Nullable<System.DateTime> dateConsumptionStart, Nullable<System.DateTime> dateConsumptionEnd)
        {
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var brandParameter = brand != null ?
                new ObjectParameter("brand", brand) :
                new ObjectParameter("brand", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var dateConsumptionStartParameter = dateConsumptionStart.HasValue ?
                new ObjectParameter("dateConsumptionStart", dateConsumptionStart) :
                new ObjectParameter("dateConsumptionStart", typeof(System.DateTime));
    
            var dateConsumptionEndParameter = dateConsumptionEnd.HasValue ?
                new ObjectParameter("dateConsumptionEnd", dateConsumptionEnd) :
                new ObjectParameter("dateConsumptionEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_Mem_ConsumptionFrequency_Count_Result>("sp_Rpt_Mem_ConsumptionFrequency_Count", channelParameter, brandParameter, categoryParameter, dateConsumptionStartParameter, dateConsumptionEndParameter);
        }
    
        public virtual ObjectResult<sp_Rpt_Mem_ContributionRate_Statistics_Result> sp_Rpt_Mem_ContributionRate_Statistics(Nullable<System.DateTime> datetime_year, Nullable<System.DateTime> datetime_month, string channel, string area, string city, string store, string memlevel)
        {
            var datetime_yearParameter = datetime_year.HasValue ?
                new ObjectParameter("datetime_year", datetime_year) :
                new ObjectParameter("datetime_year", typeof(System.DateTime));
    
            var datetime_monthParameter = datetime_month.HasValue ?
                new ObjectParameter("datetime_month", datetime_month) :
                new ObjectParameter("datetime_month", typeof(System.DateTime));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var memlevelParameter = memlevel != null ?
                new ObjectParameter("Memlevel", memlevel) :
                new ObjectParameter("Memlevel", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_Mem_ContributionRate_Statistics_Result>("sp_Rpt_Mem_ContributionRate_Statistics", datetime_yearParameter, datetime_monthParameter, channelParameter, areaParameter, cityParameter, storeParameter, memlevelParameter);
        }
    
        public virtual ObjectResult<sp_Rpt_Mem_Count_Result> sp_Rpt_Mem_Count(Nullable<System.DateTime> dateBegin, Nullable<System.DateTime> dateEnd, string channel, string area, string city, string store, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var dateBeginParameter = dateBegin.HasValue ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_Mem_Count_Result>("sp_Rpt_Mem_Count", dateBeginParameter, dateEndParameter, channelParameter, areaParameter, cityParameter, storeParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_Mem_IssuingConsumption_Result_Result> sp_Rpt_Mem_IssuingConsumption_Result(Nullable<System.DateTime> dateBegin, Nullable<System.DateTime> dateEnd, string channel, string area, string city, string store, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var dateBeginParameter = dateBegin.HasValue ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_Mem_IssuingConsumption_Result_Result>("sp_Rpt_Mem_IssuingConsumption_Result", dateBeginParameter, dateEndParameter, channelParameter, areaParameter, cityParameter, storeParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_Mem_MemToNonMemSalesDutyCount_Result> sp_Rpt_Mem_MemToNonMemSalesDutyCount(Nullable<System.DateTime> dateConsumptionStart, Nullable<System.DateTime> dateConsumptionEnd, string customSource)
        {
            var dateConsumptionStartParameter = dateConsumptionStart.HasValue ?
                new ObjectParameter("dateConsumptionStart", dateConsumptionStart) :
                new ObjectParameter("dateConsumptionStart", typeof(System.DateTime));
    
            var dateConsumptionEndParameter = dateConsumptionEnd.HasValue ?
                new ObjectParameter("dateConsumptionEnd", dateConsumptionEnd) :
                new ObjectParameter("dateConsumptionEnd", typeof(System.DateTime));
    
            var customSourceParameter = customSource != null ?
                new ObjectParameter("customSource", customSource) :
                new ObjectParameter("customSource", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_Mem_MemToNonMemSalesDutyCount_Result>("sp_Rpt_Mem_MemToNonMemSalesDutyCount", dateConsumptionStartParameter, dateConsumptionEndParameter, customSourceParameter);
        }
    
        public virtual ObjectResult<sp_Rpt_MemContributionRate_Result_Result> sp_Rpt_MemContributionRate_Result(Nullable<System.DateTime> yearDate, Nullable<System.DateTime> endDate)
        {
            var yearDateParameter = yearDate.HasValue ?
                new ObjectParameter("yearDate", yearDate) :
                new ObjectParameter("yearDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_MemContributionRate_Result_Result>("sp_Rpt_MemContributionRate_Result", yearDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<sp_Rpt_MemMonthConsum_Result> sp_Rpt_MemMonthConsum(Nullable<System.DateTime> dateBegin, Nullable<System.DateTime> dateEnd, string channel, string area, string city, string store, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var dateBeginParameter = dateBegin.HasValue ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_MemMonthConsum_Result>("sp_Rpt_MemMonthConsum", dateBeginParameter, dateEndParameter, channelParameter, areaParameter, cityParameter, storeParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_MemUpGrade_Result> sp_Rpt_MemUpGrade(Nullable<System.DateTime> dateBegin, Nullable<System.DateTime> dateEnd, string channel, string area, string city, string store, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var dateBeginParameter = dateBegin.HasValue ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_MemUpGrade_Result>("sp_Rpt_MemUpGrade", dateBeginParameter, dateEndParameter, channelParameter, areaParameter, cityParameter, storeParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_StoreConsumptionDuty_Count_Result> sp_Rpt_StoreConsumptionDuty_Count(string channel, string area, string city, string store, Nullable<System.DateTime> dateConsumptionStart, Nullable<System.DateTime> dateConsumptionEnd, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var dateConsumptionStartParameter = dateConsumptionStart.HasValue ?
                new ObjectParameter("dateConsumptionStart", dateConsumptionStart) :
                new ObjectParameter("dateConsumptionStart", typeof(System.DateTime));
    
            var dateConsumptionEndParameter = dateConsumptionEnd.HasValue ?
                new ObjectParameter("dateConsumptionEnd", dateConsumptionEnd) :
                new ObjectParameter("dateConsumptionEnd", typeof(System.DateTime));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_StoreConsumptionDuty_Count_Result>("sp_Rpt_StoreConsumptionDuty_Count", channelParameter, areaParameter, cityParameter, storeParameter, dateConsumptionStartParameter, dateConsumptionEndParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_Prd_WeChatSign_Result> sp_Rpt_Prd_WeChatSign(string dateBegin, string dateEnd, string actionCode, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var dateBeginParameter = dateBegin != null ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            var actionCodeParameter = actionCode != null ?
                new ObjectParameter("ActionCode", actionCode) :
                new ObjectParameter("ActionCode", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_Prd_WeChatSign_Result>("sp_Rpt_Prd_WeChatSign", dateBeginParameter, dateEndParameter, actionCodeParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_WXSign_Result> sp_Rpt_WXSign(string startDate, string endDate, string actionName, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var actionNameParameter = actionName != null ?
                new ObjectParameter("ActionName", actionName) :
                new ObjectParameter("ActionName", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_WXSign_Result>("sp_Rpt_WXSign", startDateParameter, endDateParameter, actionNameParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_Mem_Recruit_Count_Result> sp_Rpt_Mem_Recruit_Count(string dateRegType, Nullable<System.DateTime> dateRegDate, string channel, string area, string city, string store, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var dateRegTypeParameter = dateRegType != null ?
                new ObjectParameter("dateRegType", dateRegType) :
                new ObjectParameter("dateRegType", typeof(string));
    
            var dateRegDateParameter = dateRegDate.HasValue ?
                new ObjectParameter("dateRegDate", dateRegDate) :
                new ObjectParameter("dateRegDate", typeof(System.DateTime));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_Mem_Recruit_Count_Result>("sp_Rpt_Mem_Recruit_Count", dateRegTypeParameter, dateRegDateParameter, channelParameter, areaParameter, cityParameter, storeParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_StoreConsumptionMonthly_Count_Result> sp_Rpt_StoreConsumptionMonthly_Count(string channel, string area, string city, string store, Nullable<System.DateTime> consumptiondateStart, Nullable<System.DateTime> consumptiondateEnd, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var consumptiondateStartParameter = consumptiondateStart.HasValue ?
                new ObjectParameter("consumptiondateStart", consumptiondateStart) :
                new ObjectParameter("consumptiondateStart", typeof(System.DateTime));
    
            var consumptiondateEndParameter = consumptiondateEnd.HasValue ?
                new ObjectParameter("consumptiondateEnd", consumptiondateEnd) :
                new ObjectParameter("consumptiondateEnd", typeof(System.DateTime));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_StoreConsumptionMonthly_Count_Result>("sp_Rpt_StoreConsumptionMonthly_Count", channelParameter, areaParameter, cityParameter, storeParameter, consumptiondateStartParameter, consumptiondateEndParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_MemRepeatedConsumption_Result_Result> sp_Rpt_MemRepeatedConsumption_Result(Nullable<System.DateTime> dateBegin, Nullable<System.DateTime> dateEnd, string channel, string area, string city, string store, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var dateBeginParameter = dateBegin.HasValue ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_MemRepeatedConsumption_Result_Result>("sp_Rpt_MemRepeatedConsumption_Result", dateBeginParameter, dateEndParameter, channelParameter, areaParameter, cityParameter, storeParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_WXSign_Detail_Result> sp_Rpt_WXSign_Detail(string startDate, string endDate, string actionCode, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            var actionCodeParameter = actionCode != null ?
                new ObjectParameter("ActionCode", actionCode) :
                new ObjectParameter("ActionCode", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_WXSign_Detail_Result>("sp_Rpt_WXSign_Detail", startDateParameter, endDateParameter, actionCodeParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_Mem_ConsumerDetails_Result> sp_Rpt_Mem_ConsumerDetails(string channel, string area, string city, string store, Nullable<System.DateTime> dateConsumptionStart, Nullable<System.DateTime> dateConsumptionEnd, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var dateConsumptionStartParameter = dateConsumptionStart.HasValue ?
                new ObjectParameter("dateConsumptionStart", dateConsumptionStart) :
                new ObjectParameter("dateConsumptionStart", typeof(System.DateTime));
    
            var dateConsumptionEndParameter = dateConsumptionEnd.HasValue ?
                new ObjectParameter("dateConsumptionEnd", dateConsumptionEnd) :
                new ObjectParameter("dateConsumptionEnd", typeof(System.DateTime));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_Mem_ConsumerDetails_Result>("sp_Rpt_Mem_ConsumerDetails", channelParameter, areaParameter, cityParameter, storeParameter, dateConsumptionStartParameter, dateConsumptionEndParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_UseCoupon_Count_Result> sp_Rpt_UseCoupon_Count(string area, string city, string store, string couponname, Nullable<System.DateTime> datesendcouponStart, Nullable<System.DateTime> datesendcouponEnd, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var couponnameParameter = couponname != null ?
                new ObjectParameter("couponname", couponname) :
                new ObjectParameter("couponname", typeof(string));
    
            var datesendcouponStartParameter = datesendcouponStart.HasValue ?
                new ObjectParameter("datesendcouponStart", datesendcouponStart) :
                new ObjectParameter("datesendcouponStart", typeof(System.DateTime));
    
            var datesendcouponEndParameter = datesendcouponEnd.HasValue ?
                new ObjectParameter("datesendcouponEnd", datesendcouponEnd) :
                new ObjectParameter("datesendcouponEnd", typeof(System.DateTime));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_UseCoupon_Count_Result>("sp_Rpt_UseCoupon_Count", areaParameter, cityParameter, storeParameter, couponnameParameter, datesendcouponStartParameter, datesendcouponEndParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_PriceSegmentDistributionOffline_Result_Result> sp_Rpt_PriceSegmentDistributionOffline_Result(Nullable<System.DateTime> dateBegin, Nullable<System.DateTime> dateEnd, string channel, string area, string city, string store)
        {
            var dateBeginParameter = dateBegin.HasValue ?
                new ObjectParameter("dateBegin", dateBegin) :
                new ObjectParameter("dateBegin", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_PriceSegmentDistributionOffline_Result_Result>("sp_Rpt_PriceSegmentDistributionOffline_Result", dateBeginParameter, dateEndParameter, channelParameter, areaParameter, cityParameter, storeParameter);
        }
    
        public virtual ObjectResult<sp_Rpt_CouponDetail_Result> sp_Rpt_CouponDetail(string area, string city, string store, string grade, string channel, Nullable<System.DateTime> datesendcouponStart, Nullable<System.DateTime> datesendcouponEnd, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var gradeParameter = grade != null ?
                new ObjectParameter("grade", grade) :
                new ObjectParameter("grade", typeof(string));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var datesendcouponStartParameter = datesendcouponStart.HasValue ?
                new ObjectParameter("datesendcouponStart", datesendcouponStart) :
                new ObjectParameter("datesendcouponStart", typeof(System.DateTime));
    
            var datesendcouponEndParameter = datesendcouponEnd.HasValue ?
                new ObjectParameter("datesendcouponEnd", datesendcouponEnd) :
                new ObjectParameter("datesendcouponEnd", typeof(System.DateTime));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_CouponDetail_Result>("sp_Rpt_CouponDetail", areaParameter, cityParameter, storeParameter, gradeParameter, channelParameter, datesendcouponStartParameter, datesendcouponEndParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_MarketActivityDetail_Result> sp_Rpt_MarketActivityDetail(string area, string city, string store, string channel, Nullable<System.DateTime> marStarttime, Nullable<System.DateTime> marEndtime, Nullable<System.DateTime> comStarttime, Nullable<System.DateTime> comEndtime, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var marStarttimeParameter = marStarttime.HasValue ?
                new ObjectParameter("marStarttime", marStarttime) :
                new ObjectParameter("marStarttime", typeof(System.DateTime));
    
            var marEndtimeParameter = marEndtime.HasValue ?
                new ObjectParameter("marEndtime", marEndtime) :
                new ObjectParameter("marEndtime", typeof(System.DateTime));
    
            var comStarttimeParameter = comStarttime.HasValue ?
                new ObjectParameter("comStarttime", comStarttime) :
                new ObjectParameter("comStarttime", typeof(System.DateTime));
    
            var comEndtimeParameter = comEndtime.HasValue ?
                new ObjectParameter("comEndtime", comEndtime) :
                new ObjectParameter("comEndtime", typeof(System.DateTime));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_MarketActivityDetail_Result>("sp_Rpt_MarketActivityDetail", areaParameter, cityParameter, storeParameter, channelParameter, marStarttimeParameter, marEndtimeParameter, comStarttimeParameter, comEndtimeParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_ActIntance_Count_Result> sp_Rpt_ActIntance_Count(string area, string city, string store, string channel, Nullable<System.DateTime> dateActStart, Nullable<System.DateTime> dateActEnd, Nullable<System.DateTime> dateConsumeStart, Nullable<System.DateTime> dateConsumeEnd, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var dateActStartParameter = dateActStart.HasValue ?
                new ObjectParameter("dateActStart", dateActStart) :
                new ObjectParameter("dateActStart", typeof(System.DateTime));
    
            var dateActEndParameter = dateActEnd.HasValue ?
                new ObjectParameter("dateActEnd", dateActEnd) :
                new ObjectParameter("dateActEnd", typeof(System.DateTime));
    
            var dateConsumeStartParameter = dateConsumeStart.HasValue ?
                new ObjectParameter("dateConsumeStart", dateConsumeStart) :
                new ObjectParameter("dateConsumeStart", typeof(System.DateTime));
    
            var dateConsumeEndParameter = dateConsumeEnd.HasValue ?
                new ObjectParameter("dateConsumeEnd", dateConsumeEnd) :
                new ObjectParameter("dateConsumeEnd", typeof(System.DateTime));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_ActIntance_Count_Result>("sp_Rpt_ActIntance_Count", areaParameter, cityParameter, storeParameter, channelParameter, dateActStartParameter, dateActEndParameter, dateConsumeStartParameter, dateConsumeEndParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    
        public virtual ObjectResult<sp_Rpt_UsedCoupon_Detail_Result> sp_Rpt_UsedCoupon_Detail(string area, string city, string store, string channel, string memlevel, Nullable<System.DateTime> dateStart, Nullable<System.DateTime> dateEnd, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter recordCount)
        {
            var areaParameter = area != null ?
                new ObjectParameter("area", area) :
                new ObjectParameter("area", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var storeParameter = store != null ?
                new ObjectParameter("store", store) :
                new ObjectParameter("store", typeof(string));
    
            var channelParameter = channel != null ?
                new ObjectParameter("channel", channel) :
                new ObjectParameter("channel", typeof(string));
    
            var memlevelParameter = memlevel != null ?
                new ObjectParameter("memlevel", memlevel) :
                new ObjectParameter("memlevel", typeof(string));
    
            var dateStartParameter = dateStart.HasValue ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(System.DateTime));
    
            var dateEndParameter = dateEnd.HasValue ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(System.DateTime));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Rpt_UsedCoupon_Detail_Result>("sp_Rpt_UsedCoupon_Detail", areaParameter, cityParameter, storeParameter, channelParameter, memlevelParameter, dateStartParameter, dateEndParameter, pageIndexParameter, pageSizeParameter, recordCount);
        }
    }
}
