//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.Report.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL_WX_MemberSign
    {
        public string MemberID { get; set; }
        public string ActionName { get; set; }
        public string ActionCode { get; set; }
        public System.DateTime SignDate { get; set; }
        public int SignDate2 { get; set; }
        public string OpenID { get; set; }
        public string Mobile { get; set; }
    }
}
