//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.Report.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_TM_SYS_BaseData_product
    {
        public long BaseDataID { get; set; }
        public int DataGroupID { get; set; }
        public string BaseDataType { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductCode_IPOS { get; set; }
        public string ProductLineCode1 { get; set; }
        public string ProductLineName1Base { get; set; }
        public string ProductLineCode2 { get; set; }
        public string ProductLineName2Base { get; set; }
        public string ProductLineCode3 { get; set; }
        public string ProductLineName3 { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryName { get; set; }
        public string SubCategoryCode { get; set; }
        public string SubCategoryName { get; set; }
        public string OrginalSellPrice { get; set; }
        public string StopUsageFlag { get; set; }
        public string ProductBrandCode { get; set; }
        public string ProductBrandNameBase { get; set; }
        public string ProductStatusCode { get; set; }
        public string ProductStatusNameBase { get; set; }
        public string ProductSyncFlag { get; set; }
    }
}
