//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.Report.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_TM_SYS_BaseData_store
    {
        public long BaseDataID { get; set; }
        public int DataGroupID { get; set; }
        public string BaseDataType { get; set; }
        public string StoreName { get; set; }
        public string StoreAddress { get; set; }
        public string StoreCode { get; set; }
        public string StoreFullName { get; set; }
        public string StoreCode_IPOS { get; set; }
        public string AreaCodeStore { get; set; }
        public string AreaNameStore { get; set; }
        public string ProvinceCodeStore { get; set; }
        public string ProvinceStore { get; set; }
        public string CityCodeStore { get; set; }
        public string CityStore { get; set; }
        public string AddressStore { get; set; }
        public string ChannelCodeStore { get; set; }
        public string ChannelNameStore { get; set; }
        public string ChannelTypeCodeStore { get; set; }
        public string ChannerTypeNameStore { get; set; }
        public string StoreType { get; set; }
        public string StoreTel { get; set; }
        public string BrandStore { get; set; }
        public string OneLineFlag { get; set; }
    }
}
