//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.Report.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_TM_SYS_BaseData_customerlevel
    {
        public long BaseDataID { get; set; }
        public int DataGroupID { get; set; }
        public string BaseDataType { get; set; }
        public string CustomerLevelBase { get; set; }
        public string CustomerLevelNameBase { get; set; }
        public Nullable<decimal> RateCustomerLevel { get; set; }
        public string BrandCodeCustomerLevel { get; set; }
        public Nullable<int> MaxIntergral { get; set; }
        public string BrandNameCustomerLevel { get; set; }
        public Nullable<int> LevelUpInt { get; set; }
    }
}
