//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace arvato.CRM.SettingTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TD_SYS_BizOption> TD_SYS_BizOption { get; set; }
        public DbSet<TM_CRM_KPI> TM_CRM_KPI { get; set; }
        public DbSet<TM_CRM_KPITarget> TM_CRM_KPITarget { get; set; }
        public DbSet<TD_SYS_FieldAlias> TD_SYS_FieldAlias { get; set; }
    }
}
