//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace arvato.CRM.SettingTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_CRM_KPITarget
    {
        public long KPIID { get; set; }
        public string KPIType { get; set; }
        public string KPITypeValue { get; set; }
        public Nullable<int> IntValue1 { get; set; }
        public Nullable<decimal> DecValue1 { get; set; }
        public Nullable<decimal> DecValue2 { get; set; }
        public string StrValue1 { get; set; }
    }
}
