//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.SubdivisionEngine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23:00:00")]
        public string DIVISION_PLAN_COMPUTE_TIME {
            get {
                return ((string)(this["DIVISION_PLAN_COMPUTE_TIME"]));
            }
            set {
                this["DIVISION_PLAN_COMPUTE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1990-01-01")]
        public global::System.DateTime DIVISION_LAST_COMPUTE_TIME {
            get {
                return ((global::System.DateTime)(this["DIVISION_LAST_COMPUTE_TIME"]));
            }
            set {
                this["DIVISION_LAST_COMPUTE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23:20:00")]
        public string KPI_PLAN_COMPUTE_TIME {
            get {
                return ((string)(this["KPI_PLAN_COMPUTE_TIME"]));
            }
            set {
                this["KPI_PLAN_COMPUTE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1990-01-01")]
        public global::System.DateTime KPI_LAST_COMPUTE_TIME {
            get {
                return ((global::System.DateTime)(this["KPI_LAST_COMPUTE_TIME"]));
            }
            set {
                this["KPI_LAST_COMPUTE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int COMMAND_TIMEOUT {
            get {
                return ((int)(this["COMMAND_TIMEOUT"]));
            }
            set {
                this["COMMAND_TIMEOUT"] = value;
            }
        }
    }
}
