//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_SYS_FieldAlias
    {
        public int AliasID { get; set; }
        public string TableName { get; set; }
        public string ViewName { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string FieldAlias { get; set; }
        public string AliasType { get; set; }
        public string AliasKey { get; set; }
        public string AliasSubKey { get; set; }
        public string FieldDesc { get; set; }
        public string DictTableName { get; set; }
        public string DictTableType { get; set; }
        public bool IsFilterBySubdivision { get; set; }
        public bool IsFilterByLoyRule { get; set; }
        public bool IsFilterByLoyActionLeft { get; set; }
        public bool IsFilterByLoyActionRight { get; set; }
        public bool IsCommunicationTemplet { get; set; }
        public string ControlType { get; set; }
        public string Reg { get; set; }
        public string ComputeScript { get; set; }
        public string LogScript { get; set; }
        public Nullable<short> RunType { get; set; }
        public string DataLimitType { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ComputeSort { get; set; }
        public Nullable<int> ParameterCount { get; set; }
        public Nullable<bool> IsFilterByCouponTemplet { get; set; }
        public string ErrorTip { get; set; }
        public Nullable<bool> IsDynamicAlias { get; set; }
        public Nullable<bool> IsDegreeSource { get; set; }
        public Nullable<bool> IsDegreeTarge { get; set; }
    }
}
