//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_SYS_FieldAliasDegree
    {
        public int AliasDegeeID { get; set; }
        public string ValueDegeeType { get; set; }
        public string BasicContent { get; set; }
        public int AliasID { get; set; }
        public int Sort { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string Tablename { get; set; }
        public Nullable<int> AliasID2 { get; set; }
    }
}
