//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_SYS_FieldAliasParameter
    {
        public int ParaID { get; set; }
        public int AliasID { get; set; }
        public short ParaIndex { get; set; }
        public string Reg { get; set; }
        public string FieldType { get; set; }
        public string ControlType { get; set; }
        public string DictTableName { get; set; }
        public string DictTableType { get; set; }
        public string ParameterName { get; set; }
        public Nullable<int> UIIndex { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public string GroupType { get; set; }
        public string flag { get; set; }
    }
}
