//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_SYS_Page
    {
        public int PageID { get; set; }
        public short Sort { get; set; }
        public int MenuID { get; set; }
        public string Path { get; set; }
        public string DispNameCode { get; set; }
        public string PageDesc { get; set; }
        public bool Enable { get; set; }
        public bool Visable { get; set; }
        public string Nav { get; set; }
    }
}
