//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_SYS_FilterMapping
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public string AliasKey { get; set; }
        public string AliasKeyFilter { get; set; }
        public string AliasSubKey { get; set; }
        public string AliasSubKeyFilter { get; set; }
        public string Level { get; set; }
        public string Type { get; set; }
    }
}
