//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_SYS_WeChatConsultant
    {
        public int ConsultantID { get; set; }
        public string LoginName { get; set; }
        public string UserName { get; set; }
        public string FEmail { get; set; }
        public string FPhone { get; set; }
        public string FWeixinID { get; set; }
        public Nullable<bool> FSex { get; set; }
        public string FPosition { get; set; }
        public string FTell { get; set; }
        public Nullable<System.DateTime> FUpdateDate { get; set; }
        public string FType { get; set; }
        public string FEable { get; set; }
        public string StoreCode { get; set; }
    }
}
