//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_JPOS_CouponUsed
    {
        public string UUID { get; set; }
        public string ITEMGROUPUUID { get; set; }
        public string BILLNUMBER { get; set; }
        public Nullable<System.DateTime> AUDITTIME { get; set; }
        public System.DateTime FSTARTB { get; set; }
        public System.DateTime FFINISHB { get; set; }
        public string CONFLICTGROUP { get; set; }
        public string REMARK { get; set; }
        public string DOCUMENT { get; set; }
        public System.DateTime FSTARTP { get; set; }
        public System.DateTime FFINISHP { get; set; }
        public string PRODUCTCONDDOC { get; set; }
        public string PRODUCTEXPRESSION { get; set; }
        public string PRODUCTUUID { get; set; }
        public Nullable<decimal> QPC { get; set; }
    }
}
