//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TE_MEM_ScoreSave
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string OperatorStr { get; set; }
        public string StoreCode { get; set; }
        public string TranId { get; set; }
        public Nullable<System.DateTime> TranTime { get; set; }
        public string PosNo { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string CardType { get; set; }
        public string Media { get; set; }
        public string Xid { get; set; }
        public string Scores { get; set; }
        public string AccountAccessCode { get; set; }
        public string OldXid { get; set; }
        public Nullable<decimal> TotalScores { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
