//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL_Act_Communication
    {
        public long LogID { get; set; }
        public string MemberID { get; set; }
        public Nullable<int> TempletID { get; set; }
        public Nullable<System.DateTime> OccurTime { get; set; }
        public string ReferenceActID { get; set; }
        public string ContentDesc { get; set; }
        public bool Direction { get; set; }
        public short Status { get; set; }
        public string CommType { get; set; }
        public string Source { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public string IsSync { get; set; }
        public string SyncType { get; set; }
        public Nullable<short> RunTimes { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string WeChatSyncStatus { get; set; }
        public Nullable<short> WeChatSyncTimes { get; set; }
    }
}
