//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL_Mem_AccountChange
    {
        public long LogID { get; set; }
        public string MemberID { get; set; }
        public string AccountID { get; set; }
        public string AccountDetailID { get; set; }
        public string AccountChangeType { get; set; }
        public decimal ChangeValue { get; set; }
        public Nullable<decimal> ChangeValueBefore { get; set; }
        public string ChangeReason { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<int> RuleID { get; set; }
        public bool HasReverse { get; set; }
        public string Remark { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public string JPOSNumber { get; set; }
    }
}
