//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL_Mem_LevelChange
    {
        public long LogID { get; set; }
        public string MemberID { get; set; }
        public string ChangeLevelTo { get; set; }
        public string LevelChangeType { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public string ChangeReason { get; set; }
        public string ChangeLevelFrom { get; set; }
        public Nullable<System.DateTime> StartDateFrom { get; set; }
        public Nullable<System.DateTime> StartDateTo { get; set; }
        public Nullable<System.DateTime> EndDateFrom { get; set; }
        public Nullable<System.DateTime> EndDateTo { get; set; }
    }
}
