//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TL_Mem_CardChange
    {
        public long LogID { get; set; }
        public string CardNo { get; set; }
        public string ChangeType { get; set; }
        public System.DateTime ChangeTime { get; set; }
        public string ChangePlace { get; set; }
        public string OldCardNo { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public string Remark { get; set; }
        public string Agent { get; set; }
        public string AgentCertificateNo { get; set; }
        public string AgentMobile { get; set; }
        public Nullable<decimal> ServiceCharge { get; set; }
    }
}
