//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Act_CommunicationTemplet
    {
        public int TempletID { get; set; }
        public int DataGroupID { get; set; }
        public string SchemaId { get; set; }
        public string BusinessType { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string SubType { get; set; }
        public string Category { get; set; }
        public string Topic { get; set; }
        public string BasicContent { get; set; }
        public string IDOSPackageMapping { get; set; }
        public Nullable<decimal> InternalSetPrice { get; set; }
        public string Proportion { get; set; }
        public Nullable<decimal> MaxSetPrice { get; set; }
        public string LimitType { get; set; }
        public Nullable<int> ForeignTempletID { get; set; }
        public string Remark { get; set; }
        public short Status { get; set; }
        public bool Enable { get; set; }
        public string AddedUser { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<bool> IsSysInit { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string IsSync { get; set; }
        public Nullable<short> RunTimes { get; set; }
        public string LimitTypeKey { get; set; }
        public string ReferenceNo { get; set; }
    }
}
