//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Act_Instance
    {
        public long ActivityInstanceID { get; set; }
        public int ActivityID { get; set; }
        public int DataGroupID { get; set; }
        public string ActivityName { get; set; }
        public System.DateTime PlanStartDate { get; set; }
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        public string Workflow { get; set; }
        public Nullable<System.Guid> WfRootId { get; set; }
        public string Schedule { get; set; }
        public bool Enable { get; set; }
        public short Status { get; set; }
        public string TableName { get; set; }
        public bool IsTranslated { get; set; }
        public string Remark { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
