//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Act_InstanceStep
    {
        public System.Guid InstanceStepID { get; set; }
        public long ActivityInstanceID { get; set; }
        public Nullable<System.Guid> ParentInstanceStepID { get; set; }
        public string Category { get; set; }
        public double Wait { get; set; }
        public string ResultType { get; set; }
        public string Condition { get; set; }
        public bool SendMail { get; set; }
        public bool SendSMS { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string SendChannel { get; set; }
        public double ValidDay { get; set; }
        public System.DateTime RunDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<bool> DataLimit { get; set; }
        public string LimitType { get; set; }
        public string LimitValue { get; set; }
        public System.DateTime AddedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
