//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Card_RetrieveNew
    {
        public string RetrieveOddId { get; set; }
        public Nullable<long> RetrieveOddIdNo { get; set; }
        public string CustomizeOddId { get; set; }
        public Nullable<int> ReserveBoxNumber { get; set; }
        public string Agent { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ReserveCardNumber { get; set; }
        public string Status { get; set; }
        public string CompanyCode { get; set; }
        public string StoreCode { get; set; }
    }
}
