//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_CRM_KPIResult
    {
        public long KPIResultID { get; set; }
        public long KPIID { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public System.DateTime ComputeTime { get; set; }
        public Nullable<int> IntValue1 { get; set; }
        public Nullable<decimal> DecValue1 { get; set; }
        public string StrValue1 { get; set; }
        public string KPIType { get; set; }
        public string KPITypeValue { get; set; }
    }
}
