//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tm_Card_CardBox
    {
        public string BoxId { get; set; }
        public Nullable<int> BoxPurposeId { get; set; }
        public int CardNumIn { get; set; }
        public string BeginCardNo { get; set; }
        public string EndCardNo { get; set; }
        public string AcceptingUnit { get; set; }
        public string Remark { get; set; }
        public int Createby { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string BoxNo { get; set; }
        public string BatchNo { get; set; }
        public Nullable<bool> IsOut { get; set; }
        public Nullable<bool> IsReturn { get; set; }
        public string BoxInAddress { get; set; }
    }
}
