//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Card_Made
    {
        public string CardId { get; set; }
        public string IsExecute { get; set; }
        public string Status { get; set; }
        public string CardTypeCode { get; set; }
        public string BeginCardNum { get; set; }
        public string EndCardNum { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public int MathRule { get; set; }
        public int Production { get; set; }
        public System.DateTime ArriveTime { get; set; }
        public string BatchNo { get; set; }
        public Nullable<long> OddIdNo { get; set; }
    }
}
