//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_JPOS_ExchangeGoods
    {
        public string ExchangeID { get; set; }
        public string ExchangeType { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> MaxCounts { get; set; }
        public Nullable<int> MaxCountsDaily { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<bool> IsTotal { get; set; }
        public string Sort { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remark { get; set; }
        public string Code { get; set; }
    }
}
