//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_JPOS_CardSalesPrepare
    {
        public string id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string operatorStr { get; set; }
        public string storeCode { get; set; }
        public string tranId { get; set; }
        public Nullable<System.DateTime> tranTime { get; set; }
        public string posNo { get; set; }
        public string xid { get; set; }
        public bool isConfirm { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string cardInfo { get; set; }
        public string payRec { get; set; }
        public string confirmtradId { get; set; }
        public string canceltradId { get; set; }
        public bool isCancel { get; set; }
    }
}
