//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_JPOS_CouponPool
    {
        public string PoolID { get; set; }
        public string ListId { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> SendCount { get; set; }
        public Nullable<decimal> SendValue { get; set; }
        public Nullable<long> BeginCouponCode { get; set; }
        public Nullable<long> EndCouponCode { get; set; }
        public string FilePath { get; set; }
        public bool IsDownLoad { get; set; }
        public string FileName { get; set; }
    }
}
