//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_JPOS_PromotionItem
    {
        public string PromotionID { get; set; }
        public string BillID { get; set; }
        public string LimitMode { get; set; }
        public string LimitType { get; set; }
        public string LimitQuantity { get; set; }
        public string ProductExpression { get; set; }
        public string ProductID { get; set; }
        public string DocumentXML { get; set; }
        public string ProductXML { get; set; }
        public Nullable<decimal> QRC { get; set; }
        public string ExeCseqGroup { get; set; }
        public string ConflictGroup { get; set; }
        public string BillType { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string Stores { get; set; }
    }
}
