//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_JPOS_CouponSendRule
    {
        public int ID { get; set; }
        public Nullable<int> CouponNo { get; set; }
        public string CouponName { get; set; }
        public Nullable<decimal> CouponValue { get; set; }
        public string CouponRemark { get; set; }
        public Nullable<bool> IsMember { get; set; }
        public Nullable<bool> IsEnble { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string LimitValue { get; set; }
        public string ApproveStatus { get; set; }
        public string ExecuteStatus { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
