//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Loy_Rule
    {
        public int RuleID { get; set; }
        public string RuleName { get; set; }
        public int DataGroupID { get; set; }
        public string RuleType { get; set; }
        public string RuleRunType { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Schedule { get; set; }
        public string Condition { get; set; }
        public int RunIndex { get; set; }
        public string ConditionResult { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> LastExcuteTime { get; set; }
        public bool Enable { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string ComputeScript { get; set; }
    }
}
