//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Loy_MemExt
    {
        public string MemberID { get; set; }
        public string Str_Attr_1 { get; set; }
        public string Str_Attr_2 { get; set; }
        public string Str_Attr_3 { get; set; }
        public string Str_Attr_4 { get; set; }
        public string Str_Attr_5 { get; set; }
        public string Str_Attr_6 { get; set; }
        public string Str_Attr_7 { get; set; }
        public string Str_Attr_8 { get; set; }
        public string Str_Attr_9 { get; set; }
        public string Str_Attr_10 { get; set; }
        public string Str_Attr_11 { get; set; }
        public string Str_Attr_12 { get; set; }
        public string Str_Attr_13 { get; set; }
        public string Str_Attr_14 { get; set; }
        public string Str_Attr_15 { get; set; }
        public string Str_Attr_16 { get; set; }
        public string Str_Attr_17 { get; set; }
        public string Str_Attr_18 { get; set; }
        public string Str_Attr_19 { get; set; }
        public string Str_Attr_20 { get; set; }
        public string Str_Attr_21 { get; set; }
        public string Str_Attr_22 { get; set; }
        public string Str_Attr_23 { get; set; }
        public string Str_Attr_24 { get; set; }
        public string Str_Attr_25 { get; set; }
        public string Str_Attr_26 { get; set; }
        public string Str_Attr_27 { get; set; }
        public string Str_Attr_28 { get; set; }
        public string Str_Attr_29 { get; set; }
        public string Str_Attr_30 { get; set; }
        public string Str_Attr_31 { get; set; }
        public string Str_Attr_32 { get; set; }
        public string Str_Attr_33 { get; set; }
        public string Str_Attr_34 { get; set; }
        public string Str_Attr_35 { get; set; }
        public string Str_Attr_36 { get; set; }
        public string Str_Attr_37 { get; set; }
        public string Str_Attr_38 { get; set; }
        public string Str_Attr_39 { get; set; }
        public string Str_Attr_40 { get; set; }
        public string Str_Attr_41 { get; set; }
        public string Str_Attr_42 { get; set; }
        public string Str_Attr_43 { get; set; }
        public string Str_Attr_44 { get; set; }
        public string Str_Attr_45 { get; set; }
        public string Str_Attr_46 { get; set; }
        public string Str_Attr_47 { get; set; }
        public string Str_Attr_48 { get; set; }
        public string Str_Attr_49 { get; set; }
        public string Str_Attr_50 { get; set; }
        public Nullable<decimal> Dec_Attr_1 { get; set; }
        public Nullable<decimal> Dec_Attr_2 { get; set; }
        public Nullable<decimal> Dec_Attr_3 { get; set; }
        public Nullable<decimal> Dec_Attr_4 { get; set; }
        public Nullable<decimal> Dec_Attr_5 { get; set; }
        public Nullable<decimal> Dec_Attr_6 { get; set; }
        public Nullable<decimal> Dec_Attr_7 { get; set; }
        public Nullable<decimal> Dec_Attr_8 { get; set; }
        public Nullable<decimal> Dec_Attr_9 { get; set; }
        public Nullable<decimal> Dec_Attr_10 { get; set; }
        public Nullable<decimal> Dec_Attr_11 { get; set; }
        public Nullable<decimal> Dec_Attr_12 { get; set; }
        public Nullable<decimal> Dec_Attr_13 { get; set; }
        public Nullable<decimal> Dec_Attr_14 { get; set; }
        public Nullable<decimal> Dec_Attr_15 { get; set; }
        public Nullable<decimal> Dec_Attr_16 { get; set; }
        public Nullable<decimal> Dec_Attr_17 { get; set; }
        public Nullable<decimal> Dec_Attr_18 { get; set; }
        public Nullable<decimal> Dec_Attr_19 { get; set; }
        public Nullable<decimal> Dec_Attr_20 { get; set; }
        public Nullable<decimal> Dec_Attr_21 { get; set; }
        public Nullable<decimal> Dec_Attr_22 { get; set; }
        public Nullable<decimal> Dec_Attr_23 { get; set; }
        public Nullable<decimal> Dec_Attr_24 { get; set; }
        public Nullable<decimal> Dec_Attr_25 { get; set; }
        public Nullable<decimal> Dec_Attr_26 { get; set; }
        public Nullable<decimal> Dec_Attr_27 { get; set; }
        public Nullable<decimal> Dec_Attr_28 { get; set; }
        public Nullable<decimal> Dec_Attr_29 { get; set; }
        public Nullable<decimal> Dec_Attr_30 { get; set; }
        public Nullable<decimal> Dec_Attr_31 { get; set; }
        public Nullable<decimal> Dec_Attr_32 { get; set; }
        public Nullable<decimal> Dec_Attr_33 { get; set; }
        public Nullable<decimal> Dec_Attr_34 { get; set; }
        public Nullable<decimal> Dec_Attr_35 { get; set; }
        public Nullable<decimal> Dec_Attr_36 { get; set; }
        public Nullable<decimal> Dec_Attr_37 { get; set; }
        public Nullable<decimal> Dec_Attr_38 { get; set; }
        public Nullable<decimal> Dec_Attr_39 { get; set; }
        public Nullable<decimal> Dec_Attr_40 { get; set; }
        public Nullable<System.DateTime> Date_Attr_1 { get; set; }
        public Nullable<System.DateTime> Date_Attr_2 { get; set; }
        public Nullable<System.DateTime> Date_Attr_3 { get; set; }
        public Nullable<System.DateTime> Date_Attr_4 { get; set; }
        public Nullable<System.DateTime> Date_Attr_5 { get; set; }
        public Nullable<System.DateTime> Date_Attr_6 { get; set; }
        public Nullable<System.DateTime> Date_Attr_7 { get; set; }
        public Nullable<System.DateTime> Date_Attr_8 { get; set; }
        public Nullable<System.DateTime> Date_Attr_9 { get; set; }
        public Nullable<System.DateTime> Date_Attr_10 { get; set; }
        public Nullable<System.DateTime> Date_Attr_11 { get; set; }
        public Nullable<System.DateTime> Date_Attr_12 { get; set; }
        public Nullable<System.DateTime> Date_Attr_13 { get; set; }
        public Nullable<System.DateTime> Date_Attr_14 { get; set; }
        public Nullable<System.DateTime> Date_Attr_15 { get; set; }
        public Nullable<System.DateTime> Date_Attr_16 { get; set; }
        public Nullable<System.DateTime> Date_Attr_17 { get; set; }
        public Nullable<System.DateTime> Date_Attr_18 { get; set; }
        public Nullable<System.DateTime> Date_Attr_19 { get; set; }
        public Nullable<System.DateTime> Date_Attr_20 { get; set; }
        public Nullable<bool> Bool_Attr_1 { get; set; }
        public Nullable<bool> Bool_Attr_2 { get; set; }
        public Nullable<bool> Bool_Attr_3 { get; set; }
        public Nullable<bool> Bool_Attr_4 { get; set; }
        public Nullable<bool> Bool_Attr_5 { get; set; }
        public Nullable<bool> Bool_Attr_6 { get; set; }
        public Nullable<bool> Bool_Attr_7 { get; set; }
        public Nullable<bool> Bool_Attr_8 { get; set; }
        public Nullable<bool> Bool_Attr_9 { get; set; }
        public Nullable<bool> Bool_Attr_10 { get; set; }
        public Nullable<bool> Bool_Attr_11 { get; set; }
        public Nullable<bool> Bool_Attr_12 { get; set; }
        public Nullable<bool> Bool_Attr_13 { get; set; }
        public Nullable<bool> Bool_Attr_14 { get; set; }
        public Nullable<bool> Bool_Attr_15 { get; set; }
        public Nullable<bool> Bool_Attr_16 { get; set; }
        public Nullable<bool> Bool_Attr_17 { get; set; }
        public Nullable<bool> Bool_Attr_18 { get; set; }
        public Nullable<bool> Bool_Attr_19 { get; set; }
        public Nullable<bool> Bool_Attr_20 { get; set; }
        public Nullable<int> Int_Attr_1 { get; set; }
        public Nullable<int> Int_Attr_2 { get; set; }
        public Nullable<int> Int_Attr_3 { get; set; }
        public Nullable<int> Int_Attr_4 { get; set; }
        public Nullable<int> Int_Attr_5 { get; set; }
        public Nullable<int> Int_Attr_6 { get; set; }
        public Nullable<int> Int_Attr_7 { get; set; }
        public Nullable<int> Int_Attr_8 { get; set; }
        public Nullable<int> Int_Attr_9 { get; set; }
        public Nullable<int> Int_Attr_10 { get; set; }
        public Nullable<int> Int_Attr_11 { get; set; }
        public Nullable<int> Int_Attr_12 { get; set; }
        public Nullable<int> Int_Attr_13 { get; set; }
        public Nullable<int> Int_Attr_14 { get; set; }
        public Nullable<int> Int_Attr_15 { get; set; }
        public Nullable<int> Int_Attr_16 { get; set; }
        public Nullable<int> Int_Attr_17 { get; set; }
        public Nullable<int> Int_Attr_18 { get; set; }
        public Nullable<int> Int_Attr_19 { get; set; }
        public Nullable<int> Int_Attr_20 { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
