//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Mem_SubExt
    {
        public long MemberSubExtID { get; set; }
        public string ExtType { get; set; }
        public string MemberID { get; set; }
        public string Str_Attr_1 { get; set; }
        public string Str_Attr_2 { get; set; }
        public string Str_Attr_3 { get; set; }
        public string Str_Attr_4 { get; set; }
        public string Str_Attr_5 { get; set; }
        public string Str_Attr_6 { get; set; }
        public string Str_Attr_7 { get; set; }
        public string Str_Attr_8 { get; set; }
        public string Str_Attr_9 { get; set; }
        public string Str_Attr_10 { get; set; }
        public string Str_Attr_11 { get; set; }
        public string Str_Attr_12 { get; set; }
        public string Str_Attr_13 { get; set; }
        public string Str_Attr_14 { get; set; }
        public string Str_Attr_15 { get; set; }
        public string Str_Attr_16 { get; set; }
        public string Str_Attr_17 { get; set; }
        public string Str_Attr_18 { get; set; }
        public string Str_Attr_19 { get; set; }
        public string Str_Attr_20 { get; set; }
        public string Str_Attr_21 { get; set; }
        public string Str_Attr_22 { get; set; }
        public string Str_Attr_23 { get; set; }
        public string Str_Attr_24 { get; set; }
        public string Str_Attr_25 { get; set; }
        public string Str_Attr_26 { get; set; }
        public string Str_Attr_27 { get; set; }
        public string Str_Attr_28 { get; set; }
        public string Str_Attr_29 { get; set; }
        public string Str_Attr_30 { get; set; }
        public string Str_Attr_31 { get; set; }
        public string Str_Attr_32 { get; set; }
        public string Str_Attr_33 { get; set; }
        public string Str_Attr_34 { get; set; }
        public string Str_Attr_35 { get; set; }
        public string Str_Attr_36 { get; set; }
        public Nullable<System.DateTime> Date_Attr_1 { get; set; }
        public Nullable<System.DateTime> Date_Attr_10 { get; set; }
        public Nullable<System.DateTime> Date_Attr_11 { get; set; }
        public Nullable<System.DateTime> Date_Attr_12 { get; set; }
        public Nullable<System.DateTime> Date_Attr_13 { get; set; }
        public Nullable<System.DateTime> Date_Attr_14 { get; set; }
        public Nullable<decimal> Dec_Attr_1 { get; set; }
        public Nullable<decimal> Dec_Attr_2 { get; set; }
        public Nullable<decimal> Dec_Attr_3 { get; set; }
        public Nullable<decimal> Dec_Attr_4 { get; set; }
        public Nullable<bool> Bool_Attr_50 { get; set; }
        public Nullable<bool> Bool_Attr_51 { get; set; }
        public Nullable<System.DateTime> Date_Attr_52 { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
