//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Mem_CouponCreateQueue
    {
        public long CouponQueueID { get; set; }
        public int TemplateID { get; set; }
        public string MemberID { get; set; }
        public Nullable<long> ActInstanceID { get; set; }
        public Nullable<System.Guid> WfRootId { get; set; }
        public Nullable<int> DataGroupID { get; set; }
        public bool IsSMS { get; set; }
        public bool IsEmail { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public long CouponCreateID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CouponCode { get; set; }
    }
}
