//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Mem_CouponPool
    {
        public long CouponID { get; set; }
        public string CouponCode { get; set; }
        public string MemberID { get; set; }
        public string CouponType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Enable { get; set; }
        public bool IsUsed { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int TempletID { get; set; }
        public Nullable<long> ActInstanceID { get; set; }
        public Nullable<System.Guid> WorkflowID { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> Counts { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ReferenceNo { get; set; }
    }
}
