//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Mem_SubdivisionInstance
    {
        public System.Guid SubdivisionInstanceID { get; set; }
        public System.Guid SubdivisionID { get; set; }
        public string TableName { get; set; }
        public Nullable<int> ComputerTime { get; set; }
        public Nullable<System.DateTime> LastComputerDate { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<int> MemberCount { get; set; }
    }
}
