//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Mem_Master
    {
        public TM_Mem_Master()
        {
            this.Str_Key_4 = " ";
        }
    
        public string MemberID { get; set; }
        public string ParentMemberID { get; set; }
        public int DataGroupID { get; set; }
        public short MemberGrade { get; set; }
        public string MemberLevel { get; set; }
        public string MemberLevel2 { get; set; }
        public string Str_Key_1 { get; set; }
        public string Str_Key_2 { get; set; }
        public string Str_Key_3 { get; set; }
        public string Str_Key_4 { get; set; }
        public string Str_Key_10 { get; set; }
        public Nullable<int> Int_Key_1 { get; set; }
        public Nullable<long> Int_Key_10 { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
