//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Mem_Card
    {
        public string CardNo { get; set; }
        public string MemberID { get; set; }
        public bool Active { get; set; }
        public bool Lock { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public string CardType { get; set; }
        public Nullable<bool> IsReissured { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
