//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_POS_TradeDetailPromotion
    {
        public long TradeID { get; set; }
        public long TradeDetailID { get; set; }
        public string PromotionID { get; set; }
        public string PromotionCode { get; set; }
        public string PromotionType { get; set; }
        public long ID { get; set; }
    }
}
