//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_SYS_BlockType
    {
        public int BlockTypeID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int Grade { get; set; }
        public int PageID { get; set; }
        public string BlockType { get; set; }
        public string TableName { get; set; }
        public string AliasKey { get; set; }
        public string AliasSubKey { get; set; }
        public Nullable<bool> IsHaveDetail { get; set; }
        public string BlockName { get; set; }
        public int Sort { get; set; }
        public bool IsUsed { get; set; }
    }
}
