//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_SYS_BaseData
    {
        public long BaseDataID { get; set; }
        public int DataGroupID { get; set; }
        public string BaseDataType { get; set; }
        public string Str_Attr_1 { get; set; }
        public string Str_Attr_2 { get; set; }
        public string Str_Attr_3 { get; set; }
        public string Str_Attr_4 { get; set; }
        public string Str_Attr_5 { get; set; }
        public string Str_Attr_6 { get; set; }
        public string Str_Attr_7 { get; set; }
        public string Str_Attr_8 { get; set; }
        public string Str_Attr_9 { get; set; }
        public string Str_Attr_10 { get; set; }
        public string Str_Attr_11 { get; set; }
        public string Str_Attr_12 { get; set; }
        public string Str_Attr_13 { get; set; }
        public string Str_Attr_14 { get; set; }
        public string Str_Attr_15 { get; set; }
        public string Str_Attr_16 { get; set; }
        public string Str_Attr_17 { get; set; }
        public string Str_Attr_18 { get; set; }
        public string Str_Attr_19 { get; set; }
        public string Bool_Attr_1 { get; set; }
        public Nullable<System.DateTime> Date_Attr_10 { get; set; }
        public Nullable<decimal> Dec_Attr_1 { get; set; }
        public Nullable<decimal> Dec_Attr_2 { get; set; }
        public string Str_Attr_20 { get; set; }
        public string Str_Attr_21 { get; set; }
        public Nullable<int> Int_Attr_29 { get; set; }
        public string Str_Attr_30 { get; set; }
        public Nullable<System.DateTime> Date_Attr_31 { get; set; }
        public Nullable<int> Int_Attr_32 { get; set; }
        public Nullable<System.DateTime> Date_Attr_1 { get; set; }
        public Nullable<System.DateTime> Date_Attr_2 { get; set; }
        public string AddedUser { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string ModifiedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
