//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_TM_Mem_Trade_sales
    {
        public long TradeID { get; set; }
        public int DataGroupID { get; set; }
        public string TradeCode { get; set; }
        public string TradeType { get; set; }
        public Nullable<long> RefTradeID { get; set; }
        public string RefTradeType { get; set; }
        public string MemberID { get; set; }
        public bool NeedLoyCompute { get; set; }
        public string NoNeedLoyComputeReaseon { get; set; }
        public string PosNo { get; set; }
        public string FlowNo { get; set; }
        public string Cashier { get; set; }
        public string CardNoSales { get; set; }
        public string MemoSales { get; set; }
        public string ScrFavMode { get; set; }
        public string Dealer { get; set; }
        public string ClassNo { get; set; }
        public string ContinuousFlowNo { get; set; }
        public string SrcFlowNo { get; set; }
        public string SalesChannel { get; set; }
        public string ConsumeStoreCode { get; set; }
        public string ConsumeStoreName { get; set; }
        public string BusinessType { get; set; }
        public Nullable<System.DateTime> ListDateSales { get; set; }
        public Nullable<System.DateTime> RcvTimeSales { get; set; }
        public Nullable<System.DateTime> ClassDate { get; set; }
        public Nullable<System.DateTime> FilDate { get; set; }
        public Nullable<decimal> StdTotalSales { get; set; }
        public Nullable<decimal> ScrTotalSales { get; set; }
        public Nullable<decimal> RealAmtSales { get; set; }
        public Nullable<decimal> ScrFavValue { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ScoreSales { get; set; }
        public Nullable<bool> IsKillAllSale { get; set; }
        public Nullable<bool> IsReissured { get; set; }
        public Nullable<int> RECCNT { get; set; }
        public Nullable<int> QuantitySales { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
