//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_TM_SYS_BaseData_model
    {
        public long BaseDataID { get; set; }
        public int DataGroupID { get; set; }
        public string BaseDataType { get; set; }
        public string ModelName { get; set; }
        public string ModelCode { get; set; }
        public string SeriesCode { get; set; }
        public string BrandCode { get; set; }
    }
}
