//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_TM_Mem_Trade_invoice
    {
        public long TradeID { get; set; }
        public int DataGroupID { get; set; }
        public string TradeCode { get; set; }
        public string TradeType { get; set; }
        public Nullable<long> RefTradeID { get; set; }
        public string RefTradeType { get; set; }
        public string MemberID { get; set; }
        public bool NeedLoyCompute { get; set; }
        public string NoNeedLoyComputeReaseon { get; set; }
        public string StoreCodeInovice { get; set; }
        public string MobileNumberInvoice { get; set; }
        public string StatusInvoice { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> AmountInvoice { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string InvoiceDrawer { get; set; }
        public string InvoiceType { get; set; }
        public string CorpName { get; set; }
        public string IdentityNo { get; set; }
        public string CreditCode { get; set; }
        public string CorpAddress { get; set; }
        public string CorpMobile { get; set; }
        public string DepositBank { get; set; }
        public string BankAccount { get; set; }
        public string Memtype { get; set; }
        public string StoreCode2Inovice { get; set; }
        public string InvoiceOrderNo { get; set; }
    }
}
