//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_TM_Mem_SubExt_contact
    {
        public long MemberSubExtID { get; set; }
        public string ExtType { get; set; }
        public string MemberID { get; set; }
        public string ContactName { get; set; }
        public string ContactGender { get; set; }
        public string ContactTel { get; set; }
        public string ContactMobile { get; set; }
        public string ContactEmail { get; set; }
        public string ContactProvince { get; set; }
        public string ContactCity { get; set; }
        public string ContactDistrict { get; set; }
        public string ContactZip { get; set; }
        public string ContactJob { get; set; }
        public string LovingCommunication { get; set; }
        public string BestContactTime1 { get; set; }
        public string BestContactTime2 { get; set; }
        public string ContactPosition { get; set; }
        public string ContactIdNo { get; set; }
        public string ContactCertificateType { get; set; }
        public string ContactAddress { get; set; }
        public string ContactType { get; set; }
        public string ContactProvinceName { get; set; }
        public string ContactCityName { get; set; }
        public string ContactDistrictName { get; set; }
        public Nullable<bool> ContactHaveTrade { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
