//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_TM_Mem_SubExt_vehicle
    {
        public long MemberSubExtID { get; set; }
        public string ExtType { get; set; }
        public string MemberID { get; set; }
        public string VINVehicle { get; set; }
        public string PlateNumVehicle { get; set; }
        public string BrandVehicle { get; set; }
        public string SeriesVehicle { get; set; }
        public string LevelVehicle { get; set; }
        public string ColorVehicle { get; set; }
        public string TrimVehicle { get; set; }
        public string DriveDistinct { get; set; }
        public string IsPass { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
