//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_TM_Mem_SubExt_openid
    {
        public long MemberSubExtID { get; set; }
        public string ExtType { get; set; }
        public string MemberID { get; set; }
        public string OpenIDSubMember { get; set; }
        public string OpenIDSource { get; set; }
        public string OpenIDBK_1 { get; set; }
        public string OpenIDBK_2 { get; set; }
        public string OpenIDStatus { get; set; }
        public string OpenIDChannel { get; set; }
        public string OpenIDNickName { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public string AddedUser { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
