//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_TM_Mem_TradeDetail_sales_discount
    {
        public long TradeDetailID { get; set; }
        public string TradeDetailType { get; set; }
        public long TradeID { get; set; }
        public string TradeType { get; set; }
        public string ItemNoDiscount { get; set; }
        public string FavType { get; set; }
        public string PromNum { get; set; }
        public string PromCls { get; set; }
        public string PromOteCode { get; set; }
        public Nullable<decimal> FavAmtSalesDiscount { get; set; }
        public Nullable<decimal> PromAmt { get; set; }
        public Nullable<decimal> VouParValue { get; set; }
        public Nullable<System.DateTime> RcvTimeSalesDiscount { get; set; }
        public Nullable<int> PromQty { get; set; }
        public Nullable<int> PromTimes { get; set; }
        public Nullable<int> GiftQty { get; set; }
        public Nullable<int> VouParQty { get; set; }
        public Nullable<int> PromLine { get; set; }
    }
}
