//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_M_TM_Mem_TradeDetail_sales_product
    {
        public long TradeDetailID { get; set; }
        public string TradeDetailType { get; set; }
        public long TradeID { get; set; }
        public string TradeType { get; set; }
        public string ItemNoProducts { get; set; }
        public string GidSalesProduct { get; set; }
        public string GdCode { get; set; }
        public string GoodsNameProduct { get; set; }
        public string Wrh { get; set; }
        public string InvNo { get; set; }
        public string VbNum { get; set; }
        public string OrdFlag { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> RtlPrc { get; set; }
        public Nullable<decimal> PFURtlPrc { get; set; }
        public Nullable<decimal> StdTotalSalesProduct { get; set; }
        public Nullable<decimal> QuantityProduct { get; set; }
        public Nullable<decimal> ScrTotalSalesProduct { get; set; }
        public Nullable<decimal> AmountProduct { get; set; }
        public Nullable<decimal> ScrPrice { get; set; }
        public Nullable<decimal> IAmt { get; set; }
        public Nullable<decimal> ITax { get; set; }
        public Nullable<decimal> ListPrice { get; set; }
        public Nullable<decimal> FavAmtSalesProduct { get; set; }
        public Nullable<decimal> RealAmtSalesProduct { get; set; }
        public Nullable<System.DateTime> RcvTimeSalesProduct { get; set; }
        public Nullable<int> IQty { get; set; }
        public Nullable<int> Qty { get; set; }
    }
}
