//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_S_TM_Mem_Ext
    {
        public string MemberID { get; set; }
        public string CustomerStatus { get; set; }
        public string MemberCardNo { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobile { get; set; }
        public string RegisterStoreCode { get; set; }
        public string CustomerEmail { get; set; }
        public string Gender { get; set; }
        public string CertificateType { get; set; }
        public string CertificateNo { get; set; }
        public string BusinessDepartment { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Address2 { get; set; }
        public string CustomerType2 { get; set; }
        public string MembershipActivity { get; set; }
        public string MemberCardStatus { get; set; }
        public string Address1 { get; set; }
        public string CustomerSource { get; set; }
        public string ProvinceCodeExt { get; set; }
        public string CityCodeExt { get; set; }
        public string DistrictCodeExt { get; set; }
        public string UsedService { get; set; }
        public string MakeupFrequency { get; set; }
        public string SkinFeature { get; set; }
        public string NeededProduct { get; set; }
        public string StrMem_bk_1 { get; set; }
        public string StrMem_bk_2 { get; set; }
        public string StrMem_bk_3 { get; set; }
        public string StrMem_bk_4 { get; set; }
        public string StrMem_bk_5 { get; set; }
        public string StrMem_bk_7 { get; set; }
        public string StrMem_bk_8 { get; set; }
        public string StrMem_bk_9 { get; set; }
        public string StrMem_bk_10 { get; set; }
        public string Corp { get; set; }
        public string CBD { get; set; }
        public string OperationType { get; set; }
        public string Agent { get; set; }
        public string RegisterStoreName { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> NearlyRemindTime { get; set; }
        public Nullable<System.DateTime> NearlyShopTime { get; set; }
        public Nullable<System.DateTime> RegisterDateProtal { get; set; }
        public Nullable<System.DateTime> MemberStartDate { get; set; }
        public Nullable<bool> IsMessage { get; set; }
        public Nullable<bool> IsEmail { get; set; }
        public Nullable<bool> InfoCompletedFlag { get; set; }
        public Nullable<bool> HasChild { get; set; }
        public Nullable<bool> CellPhoneValidation { get; set; }
        public Nullable<bool> IsBirthday { get; set; }
        public Nullable<System.DateTime> MemberEndDate { get; set; }
        public Nullable<bool> MemberRightsLock { get; set; }
        public Nullable<System.DateTime> MemberLevelStartDate { get; set; }
        public Nullable<System.DateTime> MemberLevelEndDate { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
        public string SkinCareType { get; set; }
        public string MarriageStatus { get; set; }
        public string Job { get; set; }
        public string MonthlyIncome { get; set; }
        public string KnowingChennel { get; set; }
        public string NeededMessage { get; set; }
    }
}
