//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_S_TM_Loy_MemExt
    {
        public string MemberID { get; set; }
        public string OftenBuyTime { get; set; }
        public string ProductColorLike { get; set; }
        public string BrandLike { get; set; }
        public string ProductTypeLike { get; set; }
        public string StoreOftenGo { get; set; }
        public string ValueDegree { get; set; }
        public string Loyalty { get; set; }
        public string MemberActivity { get; set; }
        public string BestProductType { get; set; }
        public string BestProductMaterial { get; set; }
        public string OftenBuyTime_1N { get; set; }
        public string OftenBuyTime_2N { get; set; }
        public string OftenBuyTime_3N { get; set; }
        public string BrandLike_1N { get; set; }
        public string BrandLike_2N { get; set; }
        public string BrandLike_3N { get; set; }
        public string ProductTypeLike_1N { get; set; }
        public string ProductTypeLike_2N { get; set; }
        public string ProductTypeLike_3N { get; set; }
        public string StoreOftenGo_1N { get; set; }
        public string StoreOftenGo_2N { get; set; }
        public string StoreOftenGo_3N { get; set; }
        public string PromotionLike_1N { get; set; }
        public string PromotionLike_2N { get; set; }
        public string PromotionLike_3N { get; set; }
        public string ProductTypeLike_4N { get; set; }
        public string ProductTypeLike_5N { get; set; }
        public string BrandLike_4N { get; set; }
        public string BrandLike_5N { get; set; }
        public string ProductColorLike_1N { get; set; }
        public string ProductColorLike_2N { get; set; }
        public string ProductColorLike_3N { get; set; }
        public string ProductColorLike_4N { get; set; }
        public string ProductColorLike_5N { get; set; }
        public string OftenBuyTime_4N { get; set; }
        public string OftenBuyTime_5N { get; set; }
        public string Str_bk_1 { get; set; }
        public string Str_bk_2 { get; set; }
        public string Str_bk_3 { get; set; }
        public string Str_bk_4 { get; set; }
        public string Str_bk_5 { get; set; }
        public string Str_bk_6 { get; set; }
        public string Str_bk_7 { get; set; }
        public string Str_bk_8 { get; set; }
        public string Str_bk_9 { get; set; }
        public string Str_bk_10 { get; set; }
        public string Str_bk_11 { get; set; }
        public string Str_bk_12 { get; set; }
        public string Str_bk_13 { get; set; }
        public string Str_bk_14 { get; set; }
        public Nullable<decimal> HistoryConsumeAmount { get; set; }
        public Nullable<decimal> HistoryPoint { get; set; }
        public Nullable<decimal> ConsumptionYearly { get; set; }
        public Nullable<decimal> ActConsumption { get; set; }
        public Nullable<decimal> ActConsumption_3 { get; set; }
        public Nullable<decimal> ActConsumptionCounts { get; set; }
        public Nullable<decimal> LastConsumeMoney { get; set; }
        public Nullable<decimal> CumulativeIntegral_6 { get; set; }
        public Nullable<decimal> ConsumeIntegral_6 { get; set; }
        public Nullable<decimal> UsedIntergral { get; set; }
        public Nullable<decimal> ComeMaturityIntergral { get; set; }
        public Nullable<decimal> UpdateIntergral { get; set; }
        public Nullable<decimal> AccConsumeIntegral { get; set; }
        public Nullable<decimal> AccCumulativeIntegral { get; set; }
        public Nullable<decimal> ConsumeIntegral_24 { get; set; }
        public Nullable<decimal> EnableIntegrade { get; set; }
        public Nullable<decimal> ActConsumption_24 { get; set; }
        public Nullable<decimal> AvgMemPrice { get; set; }
        public Nullable<decimal> AvgMemQty { get; set; }
        public Nullable<decimal> AvgMemPriceHis { get; set; }
        public Nullable<decimal> DecLoy_bk_1 { get; set; }
        public Nullable<decimal> DecLoy_bk_2 { get; set; }
        public Nullable<decimal> DecLoy_bk_3 { get; set; }
        public Nullable<decimal> DecLoy_bk_4 { get; set; }
        public Nullable<decimal> DecLoy_bk_5 { get; set; }
        public Nullable<decimal> DecLoy_bk_6 { get; set; }
        public Nullable<decimal> DecLoy_bk_7 { get; set; }
        public Nullable<decimal> DecLoy_bk_8 { get; set; }
        public Nullable<decimal> DecLoy_bk_9 { get; set; }
        public Nullable<decimal> DecLoy_bk_10 { get; set; }
        public Nullable<decimal> DecLoy_bk_11 { get; set; }
        public Nullable<decimal> DecLoy_bk_12 { get; set; }
        public Nullable<decimal> DecLoy_bk_13 { get; set; }
        public Nullable<decimal> DecLoy_bk_14 { get; set; }
        public Nullable<decimal> DecLoy_bk_15 { get; set; }
        public Nullable<decimal> DecLoy_bk_16 { get; set; }
        public Nullable<decimal> DecLoy_bk_17 { get; set; }
        public Nullable<decimal> DecLoy_bk_18 { get; set; }
        public Nullable<decimal> DecLoy_bk_19 { get; set; }
        public Nullable<decimal> DecLoy_bk_20 { get; set; }
        public Nullable<System.DateTime> RecentPurchaseDate { get; set; }
        public Nullable<System.DateTime> DateLoy_bk_1 { get; set; }
        public Nullable<System.DateTime> DateLoy_bk_2 { get; set; }
        public Nullable<System.DateTime> DateLoy_bk_3 { get; set; }
        public Nullable<System.DateTime> DateLoy_bk_4 { get; set; }
        public Nullable<System.DateTime> DateLoy_bk_5 { get; set; }
        public Nullable<System.DateTime> DateLoy_bk_6 { get; set; }
        public Nullable<System.DateTime> DateLoy_bk_8 { get; set; }
        public Nullable<System.DateTime> DateLoy_bk_9 { get; set; }
        public Nullable<System.DateTime> DateLoy_bk_10 { get; set; }
        public Nullable<System.DateTime> DateLoy_bk_11 { get; set; }
        public Nullable<System.DateTime> DateLoy_bk_12 { get; set; }
        public Nullable<bool> IsBirthMonth { get; set; }
        public Nullable<bool> BoolLoy_bk_1 { get; set; }
        public Nullable<bool> BoolLoy_bk_2 { get; set; }
        public Nullable<bool> BoolLoy_bk_3 { get; set; }
        public Nullable<bool> BoolLoy_bk_4 { get; set; }
        public Nullable<bool> BoolLoy_bk_5 { get; set; }
        public Nullable<bool> BoolLoy_bk_6 { get; set; }
        public Nullable<bool> BoolLoy_bk_7 { get; set; }
        public Nullable<bool> BoolLoy_bk_8 { get; set; }
        public Nullable<bool> BoolLoy_bk_9 { get; set; }
        public Nullable<bool> BoolLoy_bk_10 { get; set; }
        public Nullable<int> ConsumptionCounts { get; set; }
        public Nullable<int> ConsumptionCounts_24 { get; set; }
        public Nullable<int> IntLoy_bk_1 { get; set; }
        public Nullable<int> IntLoy_bk_2 { get; set; }
        public Nullable<int> IntLoy_bk_3 { get; set; }
        public Nullable<int> IntLoy_bk_4 { get; set; }
        public Nullable<int> IntLoy_bk_5 { get; set; }
        public Nullable<int> IntLoy_bk_6 { get; set; }
        public Nullable<int> IntLoy_bk_7 { get; set; }
        public Nullable<int> IntLoy_bk_8 { get; set; }
        public Nullable<int> IntLoy_bk_9 { get; set; }
        public Nullable<int> IntLoy_bk_10 { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string AddedUser { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedUser { get; set; }
    }
}
