//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.CommunicateEngine.TimerSMSWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimerSMSWebService.wmgwSoap")]
    public interface wmgwSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsSpSendSmsNew", ReplyAction="*")]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewResponse MongateCsSpSendSmsNew(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsSpSendSmsNew", ReplyAction="*")]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewResponse> MongateCsSpSendSmsNewAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsSpMultixMtSend", ReplyAction="*")]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendResponse MongateCsSpMultixMtSend(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsSpMultixMtSend", ReplyAction="*")]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendResponse> MongateCsSpMultixMtSendAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetSmsExEx", ReplyAction="*")]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExResponse MongateCsGetSmsExEx(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetSmsExEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExResponse> MongateCsGetSmsExExAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetStatusReportExEx", ReplyAction="*")]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExResponse MongateCsGetStatusReportExEx(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateCsGetStatusReportExEx", ReplyAction="*")]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExResponse> MongateCsGetStatusReportExExAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateGetStatusReport", ReplyAction="*")]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportResponse MongateGetStatusReport(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateGetStatusReport", ReplyAction="*")]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportResponse> MongateGetStatusReportAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateQueryBalance", ReplyAction="*")]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceResponse MongateQueryBalance(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateQueryBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceResponse> MongateQueryBalanceAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateGetDeliver", ReplyAction="*")]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverResponse MongateGetDeliver(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MongateGetDeliver", ReplyAction="*")]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverResponse> MongateGetDeliverAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsSpSendSmsNewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsSpSendSmsNew", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequestBody Body;
        
        public MongateCsSpSendSmsNewRequest() {
        }
        
        public MongateCsSpSendSmsNewRequest(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsSpSendSmsNewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string pszMobis;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string pszMsg;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int iMobiCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pszSubPort;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SvrType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Param1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Param2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Param3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Param4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string MsgId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int ModuleId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Attime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Validtime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int RptFlag;
        
        public MongateCsSpSendSmsNewRequestBody() {
        }
        
        public MongateCsSpSendSmsNewRequestBody(
                    string userId, 
                    string password, 
                    string pszMobis, 
                    string pszMsg, 
                    int iMobiCount, 
                    string pszSubPort, 
                    string SvrType, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string Param4, 
                    string MsgId, 
                    int ModuleId, 
                    string Attime, 
                    string Validtime, 
                    int RptFlag) {
            this.userId = userId;
            this.password = password;
            this.pszMobis = pszMobis;
            this.pszMsg = pszMsg;
            this.iMobiCount = iMobiCount;
            this.pszSubPort = pszSubPort;
            this.SvrType = SvrType;
            this.Param1 = Param1;
            this.Param2 = Param2;
            this.Param3 = Param3;
            this.Param4 = Param4;
            this.MsgId = MsgId;
            this.ModuleId = ModuleId;
            this.Attime = Attime;
            this.Validtime = Validtime;
            this.RptFlag = RptFlag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsSpSendSmsNewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsSpSendSmsNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewResponseBody Body;
        
        public MongateCsSpSendSmsNewResponse() {
        }
        
        public MongateCsSpSendSmsNewResponse(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsSpSendSmsNewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MongateCsSpSendSmsNewResult;
        
        public MongateCsSpSendSmsNewResponseBody() {
        }
        
        public MongateCsSpSendSmsNewResponseBody(string MongateCsSpSendSmsNewResult) {
            this.MongateCsSpSendSmsNewResult = MongateCsSpSendSmsNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsSpMultixMtSendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsSpMultixMtSend", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequestBody Body;
        
        public MongateCsSpMultixMtSendRequest() {
        }
        
        public MongateCsSpMultixMtSendRequest(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsSpMultixMtSendRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string multixmt;
        
        public MongateCsSpMultixMtSendRequestBody() {
        }
        
        public MongateCsSpMultixMtSendRequestBody(string userId, string password, string multixmt) {
            this.userId = userId;
            this.password = password;
            this.multixmt = multixmt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsSpMultixMtSendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsSpMultixMtSendResponse", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendResponseBody Body;
        
        public MongateCsSpMultixMtSendResponse() {
        }
        
        public MongateCsSpMultixMtSendResponse(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsSpMultixMtSendResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MongateCsSpMultixMtSendResult;
        
        public MongateCsSpMultixMtSendResponseBody() {
        }
        
        public MongateCsSpMultixMtSendResponseBody(string MongateCsSpMultixMtSendResult) {
            this.MongateCsSpMultixMtSendResult = MongateCsSpMultixMtSendResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetSmsExExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetSmsExEx", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequestBody Body;
        
        public MongateCsGetSmsExExRequest() {
        }
        
        public MongateCsGetSmsExExRequest(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetSmsExExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public MongateCsGetSmsExExRequestBody() {
        }
        
        public MongateCsGetSmsExExRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetSmsExExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetSmsExExResponse", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExResponseBody Body;
        
        public MongateCsGetSmsExExResponse() {
        }
        
        public MongateCsGetSmsExExResponse(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetSmsExExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateCsGetSmsExExResult;
        
        public MongateCsGetSmsExExResponseBody() {
        }
        
        public MongateCsGetSmsExExResponseBody(Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateCsGetSmsExExResult) {
            this.MongateCsGetSmsExExResult = MongateCsGetSmsExExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetStatusReportExExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetStatusReportExEx", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequestBody Body;
        
        public MongateCsGetStatusReportExExRequest() {
        }
        
        public MongateCsGetStatusReportExExRequest(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetStatusReportExExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public MongateCsGetStatusReportExExRequestBody() {
        }
        
        public MongateCsGetStatusReportExExRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateCsGetStatusReportExExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateCsGetStatusReportExExResponse", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExResponseBody Body;
        
        public MongateCsGetStatusReportExExResponse() {
        }
        
        public MongateCsGetStatusReportExExResponse(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateCsGetStatusReportExExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateCsGetStatusReportExExResult;
        
        public MongateCsGetStatusReportExExResponseBody() {
        }
        
        public MongateCsGetStatusReportExExResponseBody(Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateCsGetStatusReportExExResult) {
            this.MongateCsGetStatusReportExExResult = MongateCsGetStatusReportExExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateGetStatusReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateGetStatusReport", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequestBody Body;
        
        public MongateGetStatusReportRequest() {
        }
        
        public MongateGetStatusReportRequest(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateGetStatusReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MsgId;
        
        public MongateGetStatusReportRequestBody() {
        }
        
        public MongateGetStatusReportRequestBody(string userId, string password, string MsgId) {
            this.userId = userId;
            this.password = password;
            this.MsgId = MsgId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateGetStatusReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateGetStatusReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportResponseBody Body;
        
        public MongateGetStatusReportResponse() {
        }
        
        public MongateGetStatusReportResponse(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateGetStatusReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateGetStatusReportResult;
        
        public MongateGetStatusReportResponseBody() {
        }
        
        public MongateGetStatusReportResponseBody(Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateGetStatusReportResult) {
            this.MongateGetStatusReportResult = MongateGetStatusReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateQueryBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateQueryBalance", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequestBody Body;
        
        public MongateQueryBalanceRequest() {
        }
        
        public MongateQueryBalanceRequest(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateQueryBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public MongateQueryBalanceRequestBody() {
        }
        
        public MongateQueryBalanceRequestBody(string userId, string password) {
            this.userId = userId;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateQueryBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateQueryBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceResponseBody Body;
        
        public MongateQueryBalanceResponse() {
        }
        
        public MongateQueryBalanceResponse(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateQueryBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int MongateQueryBalanceResult;
        
        public MongateQueryBalanceResponseBody() {
        }
        
        public MongateQueryBalanceResponseBody(int MongateQueryBalanceResult) {
            this.MongateQueryBalanceResult = MongateQueryBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateGetDeliverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateGetDeliver", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequestBody Body;
        
        public MongateGetDeliverRequest() {
        }
        
        public MongateGetDeliverRequest(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateGetDeliverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iReqType;
        
        public MongateGetDeliverRequestBody() {
        }
        
        public MongateGetDeliverRequestBody(string userId, string password, int iReqType) {
            this.userId = userId;
            this.password = password;
            this.iReqType = iReqType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MongateGetDeliverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MongateGetDeliverResponse", Namespace="http://tempuri.org/", Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverResponseBody Body;
        
        public MongateGetDeliverResponse() {
        }
        
        public MongateGetDeliverResponse(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MongateGetDeliverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateGetDeliverResult;
        
        public MongateGetDeliverResponseBody() {
        }
        
        public MongateGetDeliverResponseBody(Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateGetDeliverResult) {
            this.MongateGetDeliverResult = MongateGetDeliverResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wmgwSoapChannel : Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wmgwSoapClient : System.ServiceModel.ClientBase<Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap>, Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap {
        
        public wmgwSoapClient() {
        }
        
        public wmgwSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wmgwSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wmgwSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wmgwSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewResponse Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateCsSpSendSmsNew(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequest request) {
            return base.Channel.MongateCsSpSendSmsNew(request);
        }
        
        public string MongateCsSpSendSmsNew(
                    string userId, 
                    string password, 
                    string pszMobis, 
                    string pszMsg, 
                    int iMobiCount, 
                    string pszSubPort, 
                    string SvrType, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string Param4, 
                    string MsgId, 
                    int ModuleId, 
                    string Attime, 
                    string Validtime, 
                    int RptFlag) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.pszMobis = pszMobis;
            inValue.Body.pszMsg = pszMsg;
            inValue.Body.iMobiCount = iMobiCount;
            inValue.Body.pszSubPort = pszSubPort;
            inValue.Body.SvrType = SvrType;
            inValue.Body.Param1 = Param1;
            inValue.Body.Param2 = Param2;
            inValue.Body.Param3 = Param3;
            inValue.Body.Param4 = Param4;
            inValue.Body.MsgId = MsgId;
            inValue.Body.ModuleId = ModuleId;
            inValue.Body.Attime = Attime;
            inValue.Body.Validtime = Validtime;
            inValue.Body.RptFlag = RptFlag;
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewResponse retVal = ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateCsSpSendSmsNew(inValue);
            return retVal.Body.MongateCsSpSendSmsNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewResponse> Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateCsSpSendSmsNewAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequest request) {
            return base.Channel.MongateCsSpSendSmsNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewResponse> MongateCsSpSendSmsNewAsync(
                    string userId, 
                    string password, 
                    string pszMobis, 
                    string pszMsg, 
                    int iMobiCount, 
                    string pszSubPort, 
                    string SvrType, 
                    string Param1, 
                    string Param2, 
                    string Param3, 
                    string Param4, 
                    string MsgId, 
                    int ModuleId, 
                    string Attime, 
                    string Validtime, 
                    int RptFlag) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpSendSmsNewRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.pszMobis = pszMobis;
            inValue.Body.pszMsg = pszMsg;
            inValue.Body.iMobiCount = iMobiCount;
            inValue.Body.pszSubPort = pszSubPort;
            inValue.Body.SvrType = SvrType;
            inValue.Body.Param1 = Param1;
            inValue.Body.Param2 = Param2;
            inValue.Body.Param3 = Param3;
            inValue.Body.Param4 = Param4;
            inValue.Body.MsgId = MsgId;
            inValue.Body.ModuleId = ModuleId;
            inValue.Body.Attime = Attime;
            inValue.Body.Validtime = Validtime;
            inValue.Body.RptFlag = RptFlag;
            return ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateCsSpSendSmsNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendResponse Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateCsSpMultixMtSend(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequest request) {
            return base.Channel.MongateCsSpMultixMtSend(request);
        }
        
        public string MongateCsSpMultixMtSend(string userId, string password, string multixmt) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.multixmt = multixmt;
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendResponse retVal = ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateCsSpMultixMtSend(inValue);
            return retVal.Body.MongateCsSpMultixMtSendResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendResponse> Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateCsSpMultixMtSendAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequest request) {
            return base.Channel.MongateCsSpMultixMtSendAsync(request);
        }
        
        public System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendResponse> MongateCsSpMultixMtSendAsync(string userId, string password, string multixmt) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsSpMultixMtSendRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.multixmt = multixmt;
            return ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateCsSpMultixMtSendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExResponse Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateCsGetSmsExEx(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequest request) {
            return base.Channel.MongateCsGetSmsExEx(request);
        }
        
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateCsGetSmsExEx(string userId, string password) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExResponse retVal = ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateCsGetSmsExEx(inValue);
            return retVal.Body.MongateCsGetSmsExExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExResponse> Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateCsGetSmsExExAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequest request) {
            return base.Channel.MongateCsGetSmsExExAsync(request);
        }
        
        public System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExResponse> MongateCsGetSmsExExAsync(string userId, string password) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetSmsExExRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            return ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateCsGetSmsExExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExResponse Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateCsGetStatusReportExEx(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequest request) {
            return base.Channel.MongateCsGetStatusReportExEx(request);
        }
        
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateCsGetStatusReportExEx(string userId, string password) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExResponse retVal = ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateCsGetStatusReportExEx(inValue);
            return retVal.Body.MongateCsGetStatusReportExExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExResponse> Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateCsGetStatusReportExExAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequest request) {
            return base.Channel.MongateCsGetStatusReportExExAsync(request);
        }
        
        public System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExResponse> MongateCsGetStatusReportExExAsync(string userId, string password) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateCsGetStatusReportExExRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            return ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateCsGetStatusReportExExAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportResponse Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateGetStatusReport(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequest request) {
            return base.Channel.MongateGetStatusReport(request);
        }
        
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateGetStatusReport(string userId, string password, string MsgId) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.MsgId = MsgId;
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportResponse retVal = ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateGetStatusReport(inValue);
            return retVal.Body.MongateGetStatusReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportResponse> Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateGetStatusReportAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequest request) {
            return base.Channel.MongateGetStatusReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportResponse> MongateGetStatusReportAsync(string userId, string password, string MsgId) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetStatusReportRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.MsgId = MsgId;
            return ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateGetStatusReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceResponse Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateQueryBalance(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequest request) {
            return base.Channel.MongateQueryBalance(request);
        }
        
        public int MongateQueryBalance(string userId, string password) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceResponse retVal = ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateQueryBalance(inValue);
            return retVal.Body.MongateQueryBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceResponse> Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateQueryBalanceAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequest request) {
            return base.Channel.MongateQueryBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceResponse> MongateQueryBalanceAsync(string userId, string password) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateQueryBalanceRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            return ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateQueryBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverResponse Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateGetDeliver(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequest request) {
            return base.Channel.MongateGetDeliver(request);
        }
        
        public Arvato.CRM.CommunicateEngine.TimerSMSWebService.ArrayOfString MongateGetDeliver(string userId, string password, int iReqType) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.iReqType = iReqType;
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverResponse retVal = ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateGetDeliver(inValue);
            return retVal.Body.MongateGetDeliverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverResponse> Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap.MongateGetDeliverAsync(Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequest request) {
            return base.Channel.MongateGetDeliverAsync(request);
        }
        
        public System.Threading.Tasks.Task<Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverResponse> MongateGetDeliverAsync(string userId, string password, int iReqType) {
            Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequest inValue = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequest();
            inValue.Body = new Arvato.CRM.CommunicateEngine.TimerSMSWebService.MongateGetDeliverRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.iReqType = iReqType;
            return ((Arvato.CRM.CommunicateEngine.TimerSMSWebService.wmgwSoap)(this)).MongateGetDeliverAsync(inValue);
        }
    }
}
