//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.CRM.LoyaltyEngine.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23:25:00")]
        public string FREEZE_TO_AVAI {
            get {
                return ((string)(this["FREEZE_TO_AVAI"]));
            }
            set {
                this["FREEZE_TO_AVAI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1988-12-26")]
        public global::System.DateTime LAST_CHANGE_FREEZE_TIME {
            get {
                return ((global::System.DateTime)(this["LAST_CHANGE_FREEZE_TIME"]));
            }
            set {
                this["LAST_CHANGE_FREEZE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23:40:00")]
        public string AVAI_TO_ZERO {
            get {
                return ((string)(this["AVAI_TO_ZERO"]));
            }
            set {
                this["AVAI_TO_ZERO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1990-01-01")]
        public global::System.DateTime LAST_CHANGE_AVAI_TIME {
            get {
                return ((global::System.DateTime)(this["LAST_CHANGE_AVAI_TIME"]));
            }
            set {
                this["LAST_CHANGE_AVAI_TIME"] = value;
            }
        }
    }
}
